Implement filtering broker pacts by tag
reecetech/pactman pull request #65
Opened 2019-06-07 05:10 UTC by richard-reece

Closes #62

2019-06-07 05:52 UTC, ghost approved these changes

2019-06-12 15:27 UTC, MatthewMiele commented
Looks like it will also close https://github.com/reecetech/pactman/issues/35 ?

2019-06-12 22:33 UTC, RobbieClarken requested changes

2019-06-12 22:33 UTC, RobbieClarken commented on pactman/verifier/pytest_plugin.py
> +                          'multiple times to further restrict the set of pacts.')
I think "May be specified multiple times to further restrict the set of pacts" should be something like "May be specified multiple times in which case pacts matching any of these tags will be verified."

2019-06-19 08:42 UTC, RobbieClarken approved these changes

2019-06-20 22:35 UTC, merged